# Conhecendo o Python

Bem-vindo(a) ao estudo da linguagem Python

Podemos usar fómulas matemáticas com o Markdown

$$ \int_a^{b}f(x)dx $$

---

In [10]:
x = 1 
y = 2.57
print("x vale ", x)
print("y vale ", y)

x vale  1
y vale  2.57

In [11]:
x+y

3.57

In [13]:
x = "Data "
y = "Science"

print(x+y)

Data Science

In [8]:
True + True + False

2

In [9]:
None

## Conhecendo os Tipos

In [18]:
teste = [1,1]
type(teste)

list

In [22]:
int(3.99)

3

## Trabalhando com o pandas

In [26]:
import pandas as pd
import numpy as np

serie = pd.Series([3,7,5,6,"teste",8, np.nan])
serie

0        3
1        7
2        5
3        6
4    teste
5        8
6      NaN
dtype: object

In [28]:
serie.head(3)

0    3
1    7
2    5
dtype: object

In [30]:
serie.tail(2)

5      8
6    NaN
dtype: object

In [35]:
serie.dtype

dtype('O')

In [36]:
serie.isnull()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [37]:
serie[serie.isnull()]

6    NaN
dtype: object

In [39]:
serie.value_counts()

3        1
7        1
5        1
6        1
teste    1
8        1
Name: count, dtype: int64

In [44]:
data_int = pd.date_range("20250101", periods=6, freq="ME")

In [ ]:
data_br = data_int.strftime("%d/%m/%Y")
data_br

Index(['31/01/2025', '28/02/2025', '31/03/2025', '30/04/2025', '31/05/2025',
       '30/06/2025'],
      dtype='object')

In [73]:
df= pd.DataFrame(
    np.random.randint(1,5,size=(6,4)),
    index=data_br,
    columns=["A", "B", "C", "D"])

In [74]:
df.head(3)

            A  B  C  D
31/01/2025  4  1  4  1
28/02/2025  2  3  4  4
31/03/2025  1  3  3  1

In [75]:
df.columns = ['a', 'b', 'c', 'd']

In [76]:
df.columns = ['col1', 'col2', 'col3', 'col4']

In [80]:
df['Col5'] = pd.Series([1,2,3,4,5,6], index=data_br)

In [81]:
df

            col1  col2  col3  col4  Col5
31/01/2025     4     1     4     1     1
28/02/2025     2     3     4     4     2
31/03/2025     1     3     3     1     3
30/04/2025     1     2     4     1     4
31/05/2025     2     2     1     1     5
30/06/2025     4     3     4     3     6

In [82]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, 31/01/2025 to 30/06/2025
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   col1    6 non-null      int32
 1   col2    6 non-null      int32
 2   col3    6 non-null      int32
 3   col4    6 non-null      int32
 4   Col5    6 non-null      int64
dtypes: int32(4), int64(1)
memory usage: 364.0+ bytes

In [83]:
df.describe()

           col1      col2      col3      col4      Col5
count  6.000000  6.000000  6.000000  6.000000  6.000000
mean   2.333333  2.333333  3.333333  1.833333  3.500000
std    1.366260  0.816497  1.211060  1.329160  1.870829
min    1.000000  1.000000  1.000000  1.000000  1.000000
25%    1.250000  2.000000  3.250000  1.000000  2.250000
50%    2.000000  2.500000  4.000000  1.000000  3.500000
75%    3.500000  3.000000  4.000000  2.500000  4.750000
max    4.000000  3.000000  4.000000  4.000000  6.000000

In [88]:
df['Col6'] = pd.Series(['c','b','c','d','e','f'], index=data_br)

In [89]:
df.describe()

           col1      col2      col3      col4      Col5
count  6.000000  6.000000  6.000000  6.000000  6.000000
mean   2.333333  2.333333  3.333333  1.833333  3.500000
std    1.366260  0.816497  1.211060  1.329160  1.870829
min    1.000000  1.000000  1.000000  1.000000  1.000000
25%    1.250000  2.000000  3.250000  1.000000  2.250000
50%    2.000000  2.500000  4.000000  1.000000  3.500000
75%    3.500000  3.000000  4.000000  2.500000  4.750000
max    4.000000  3.000000  4.000000  4.000000  6.000000

In [90]:
df.describe(include="O")

       Col6
count     6
unique    5
top       c
freq      2